name: ld-r deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "odp-reactor-ldr" #Must be unique in Heroku
          heroku_email: "odpreactor00@protonmail.com"
          branch: "develop"
        env:
          NODE_ENV: production
          CONFIG_SPARQL_ENDPOINT_URI: https://arco.istc.cnr.it/odpr/sparql
          CONFIG_SPARQL_ENDPOINT_HOST: arco.istc.cnr.it
          CONFIG_SPARQL_ENDPOINT_PATH: /odpr/sparql
          CONFIG_SPARQL_ENDPOINT_PORT: 443
          CONFIG_SPARQL_ENDPOINT_TYPE: virtuoso
          CONFIG_SPARQL_ENDPOINT_PROTOCOL: "https"
          CONFIG_GRAPH: http://odpreactor.arco.istc.cnr.it/configuration
          ODP_REACTOR_GRAPH_HOST: https://odp-reactor-browser.vercel.app
          ODP_REACTOR_GRAPH_PORT: 443
          TEST_SPARQL_ENDPOINT_URI: https://arco.istc.cnr.it/odpr/sparql
          HOST: https://odp-reactor-ldr.herokuapp.com/
          PORT: 443
